# GitHub Actions: https://help.github.com/en/articles/workflow-syntax-for-github-actions
# Build and push Docker images Action: https://github.com/marketplace/actions/build-and-push-docker-images

name: Publish Docker image

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

env:
  DOCKER_REPO: jslee02/diffdart-dev # https://hub.docker.com/repository/docker/jslee02/diffdart-dev

jobs:
  bionic-v0_0:
    name: bionic-v0.0
    runs-on: ubuntu-latest
    env:
      BASE_IMAGE_NAME: ubuntu
      BASE_IMAGE_VERSION: bionic
      DIFFDART_VERSION: v0.0
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./${{ env.DIFFDART_VERSION }}/Dockerfile.${{ env.BASE_IMAGE_NAME }}.${{ env.BASE_IMAGE_VERSION }}
          build-args: |
            DEBIAN_FRONTEND=noninteractive
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ env.BASE_IMAGE_NAME }}-${{ env.BASE_IMAGE_VERSION }}-${{ env.DIFFDART_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  focal-v0_0:
    name: focal-v0.0
    runs-on: ubuntu-latest
    env:
      BASE_IMAGE_NAME: ubuntu
      BASE_IMAGE_VERSION: focal
      DIFFDART_VERSION: v0.0
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./${{ env.DIFFDART_VERSION }}/Dockerfile.${{ env.BASE_IMAGE_NAME }}.${{ env.BASE_IMAGE_VERSION }}
          build-args: |
            DEBIAN_FRONTEND=noninteractive
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ env.BASE_IMAGE_NAME }}-${{ env.BASE_IMAGE_VERSION }}-${{ env.DIFFDART_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  groovy-v0_0:
    name: groovy-v0.0
    runs-on: ubuntu-latest
    env:
      BASE_IMAGE_NAME: ubuntu
      BASE_IMAGE_VERSION: groovy
      DIFFDART_VERSION: v0.0
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./${{ env.DIFFDART_VERSION }}/Dockerfile.${{ env.BASE_IMAGE_NAME }}.${{ env.BASE_IMAGE_VERSION }}
          build-args: |
            DEBIAN_FRONTEND=noninteractive
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ env.BASE_IMAGE_NAME }}-${{ env.BASE_IMAGE_VERSION }}-${{ env.DIFFDART_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
